# Generated by Django 3.2.3 on 2021-06-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='hashtag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kun.hashtags'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='blogimages'),
        ),
    ]
