# Generated by Django 3.2.3 on 2021-07-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kun', '0002_auto_20210630_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='hashtag',
            new_name='hashtags',
        ),
    ]
