# Generated by Django 3.2.3 on 2021-07-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kun', '0003_rename_hashtag_blog_hashtags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hashtags',
            new_name='Hashtag',
        ),
    ]
